spring:
  #    host: localhost
#    port: 6379
#    database: 0
#    password: 1234
  cache:
    type: redis
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: guest
#    password: guest
  batch:
    job:
      enabled: false
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      password: 1q2w3e4r@




